/* InsertionTypes */
const NUMERIC_INSERTION = "NUMERIC";
const VECTORIAL_INSERTION = "VECTORIAL";
const OPERATION_INSERTION = "OPERATIONAL";
const CLEAR_INSERTION = "CLEAR";
const DELETE_LAST_INSERTION = "DELETE";

export {
  NUMERIC_INSERTION,
  OPERATION_INSERTION,
  CLEAR_INSERTION,
  DELETE_LAST_INSERTION,
  VECTORIAL_INSERTION,
};
